export const generalInfo = {
  name: {
    type: "text",
    value: "",
    label: "What is your name?",
    name: "name",
    placeholder: "Your name",
    required: true,
  },
  age: {
    type: "number",
    value: "",
    label: "What is your age?",
    name: "age",
    placeholder: "Your Age",
    required: true,
  },
  email: {
    type: "email",
    value: "",
    label: "What is your email",
    name: "email",
    placeholder: "Your email",
    required: true,
  },
  phone: {
    type: "text",
    value: "",
    label: "What is your phone number",
    name: "phone",
    placeholder: "Mobile number",
    required: true,
  },
  universty: {
    type: "text",
    value: "",
    label: "What is your University/School",
    name: "universty",
    placeholder: "University/School",
    required: true,
  },
  id: {
    type: "text",
    value: "",
    label: "If Nile Universty, What is your ID?",
    placeholder: "NU ID",
    required: false,
  },
  faculty: {
    type: "text",
    value: "",
    label: "If you are a Universty student, What is your Faculty",
    name: "faculty",
    placeholder: "Your Faculty",
    required: false,
  },
  ieeeinfo: {
    type: "textarea",
    value: "",
    label: "What do you know about IEEE?",
    name: "ieeeinfo",
    placeholder: "What do you know about IEEE?",
    required: true,
  },
  ieeeAdd: {
    type: "textarea",
    value: "",
    label: "What do you expect to add to our community?",
    name: "ieeeadd",
    placeholder: "What do you expect to add to our community?",
    required: true,
  },
  ieeeAcceptance: {
    type: "textarea",
    value: "",
    label: "Why should We accept you?",
    name: "ieeeAcceptance",
    placeholder: "Why should We accept you?",
    required: true,
  },
  committee: {
    type: "select",
    value: "",
    label: "Which committee are you applying for?",
    options: [
      "HR committee",
      "Secretary",
      "PR committee",
      "Media committee",
      "Marketing committee",
      "Technical committee",
      "Operations committee",
    ],
    name: "committie",
    required: true,
  },
};

export const hrInfo = {
  whyHR: {
    type: "textarea",
    value: "",
    label: "Why did you decide to acquire the HR position?",
    placeholder:
      "Ex: I'd like to join HR team because I'm good at analysing people...",
    required: true,
  },
  disobey: {
    type: "textarea",
    value: "",
    label:
      "State situations in which you had to deviate from policy or not to follow it.",
    name: "disobey",
    placeholder: "Once I did...",
    required: true,
  },
  swot: {
    type: "textarea",
    value: "",
    label: "What is your knowledge about SWOT analysis?",
    name: "swot",
    placeholder: "SWOT analysis is ...",
    required: true,
  },
  workforce: {
    type: "textarea",
    value: "",
    label: "What does workforce development mean?",
    name: "workforce",
    placeholder: "Workforce development is ...",
    required: true,
  },
};

export const secretaryInfo = {
  helpful: {
    type: "textarea",
    value: "",
    label: "How helpful are you?",
    description:
      "We want our members to be impactful in their committees and in their work. Tell us something you are willing to do to impact and change your committee for the better. This could be teaching your partners something or leading/suggesting a certain idea that you think will help the branch and the NU community as a whole.",
    name: "helpful",
    placeholder: "I'm thinking of...",
    required: true,
  },
  nickname: {
    type: "text",
    value: "",
    label: "What are you usually known for among your friends?",
    name: "nickname",
    placeholder: "I have a nickname...",
    required: true,
  },
};

export const prInfo = {
  prSkills: {
    type: "textarea",
    value: "",
    label: "What are the required skills/duties for PR specialist?",
    name: "prSkills",
    placeholder: "PR specialist should be...",
    required: true,
  },
  havePrSkills: {
    type: "textarea",
    value: "",
    label: "Do you have them?",
    name: "prSkills",
    placeholder: "Elaborate.",
    required: true,
  },
  prAction: {
    type: "textarea",
    value: "",
    label:
      "If you're asked to recruit a speaker to talk about AI and Machine Learning, what are the steps you're going to take?",
    name: "prAction",
    placeholder: "I'm gonna...",
    required: true,
  },
};

export const mediaInfo = {
  mediaSkills: {
    type: "select",
    value: "",
    label: "Do you have any previous experience in Media?",
    name: "mediaSkills",
    options: [true, false],
    required: true,
  },
  ifMediaSkills: {
    type: "textarea",
    value: "",
    label: "Please mention your skills.",
    name: "ifMediaSkills",
    placeholder: "I Worked as...",
    prerequisite: true,
    required: false,
  },
  designSoftwareCheck: {
    type: "check",
    value: [],
    label: "What design software do you use",
    name: "designSoftwareCheck",
    options: [
      "Photoshop",
      "Illustrator",
      "Indesign",
      "Lightroom",
      "Premier Pro",
      "After Effects",
      "Davinci resolve",
      "Final Cut pro",
      "Other",
    ],
    required: true,
  },
  otherDesignSoftware: {
    type: "textarea",
    value: "",
    label:
      "If you have any experience with other video editing/graphic design programs, mention them.",
    name: "otherDesignSoftware",
    placeholder: "I used...",
    required: false,
  },
  photoshopIllustrator: {
    type: "textarea",
    value: "",
    label:
      "What is the difference between Adobe Photoshop and Adobe Illustrator? Which one is better?",
    name: "photoshopIllustrator",
    placeholder: "The difference is...",
    required: true,
  },
  designKnowledge: {
    type: "textarea",
    value: "",
    label: "What is the difference between Brand, Logo, and Visual identity?",
    name: "designKnowledge",
    placeholder: "The difference is...",
    required: true,
  },
  mediaPortfolio: {
    type: "text",
    value: "",
    label: "Upload your portfolio (Behance or drive).",
    name: "mediaPortfolio",
    placeholder: "drive.google.com/.....",
    required: true,
  },
};

export const marketingInfo = {
  marketingSkills: {
    type: "select",
    value: "",
    label:
      "Do you have any previous experience in social media and digital marketing?",
    name: "marketingSkills",
    options: [true, false],
    required: true,
  },
  ifMarketingSkills: {
    type: "textarea",
    value: "",
    label: "Please mention your skills.",
    name: "ifMarketingSkills",
    placeholder: "I made a...",
    prerequisite: true,
    required: false,
  },
  marketingEff: {
    type: "textarea",
    value: "",
    label: "How do we measure the effectiveness of content marketing?",
    name: "marketingEff",
    placeholder: "It's measured by...",
    required: true,
  },
  facebookPost: {
    type: "textarea",
    value: "",
    label: "How to structure a perfect Facebook post?",
    name: "facebookPost",
    placeholder: "Facebook posts should have...",
    required: true,
  },
  englishLevel: {
    type: "textarea",
    value: "",
    label: "Rate your English proficiency?",
    name: "englishLevel",
    placeholder: "I'm comfort with the basis of english and...",
    required: true,
  },
};

export const operationsInfo = {
  operationsExp: {
    type: "textarea",
    value: "",
    label:
      "Can you share an experience in which you had to gather information from several sources to find the solution to a problem?",
    name: "operationsSkills",
    placeholder: "I did once...",
    required: true,
  },
  networkingSkills: {
    type: "textarea",
    value: "",
    label: "Do you have strong networking skills? Elaborate.",
    name: "networkingSkills",
    placeholder: "I did once...",
    required: true,
  },
  timeMangement: {
    type: "textarea",
    value: "",
    label: "What strategies do you use to effectively manage your time?",
    name: "timeMangement",
    placeholder: "I use planning softwares like notion, ...",
    required: true,
  },
  logisticsImpo: {
    type: "textarea",
    value: "",
    label:
      "Why do you think logistics is such an important part of an organization?",
    name: "logisticsImpo",
    placeholder: "It's very important due to...",
    required: true,
  },
};

export const technicalInfo = {
  microExperience: {
    type: "select",
    label: "Do you have experience in arduino or microcontrollers?",
    value: "",
    name: "microExperience",
    options: [true, false],
    required: true,
  },
  ifMicroExperience: {
    type: "textarea",
    value: "",
    label: "Please mention the Arduino-controlled projects you worked on.",
    placeholder: "I made an automation system to control...",
    name: "ifMicroExperience",
    prerequisite: true,
    required: false,
  },
  roboticsExperience: {
    type: "select",
    label: "Do you have any experience in the robotics field?",
    value: "",
    name: "roboticsExperience",
    options: [true, false],
    required: true,
  },
  ifRoboticsExperience: {
    type: "textarea",
    value: "",
    label: "What courses did you take in the robotics field?",
    placeholder: "I take courses at...",
    name: "roboticsExperience",
    prerequisite: true,
    required: true,
  },
  programmingExperience: {
    type: "select",
    label: "Do you have any experience in programming?",
    value: "",
    name: "programmingExperience",
    options: [true, false],
    required: true,
  },
  ifProgrammingExperience: {
    type: "textarea",
    value: "",
    label: "Which programming languages do you use?",
    placeholder: "I use javascript and ...",
    name: "ifProgrammingExperience",
    prerequisite: true,
    required: false,
  },
  webDevExp: {
    type: "select",
    label: "Do you have any experience in web development?",
    value: "",
    name: "webDevExp",
    options: [true, false],
    required: true,
  },
  ifwebDevExp: {
    type: "textarea",
    value: "",
    label: "What technologies do you use?",
    placeholder: "I use React.js and ...",
    name: "ifwebDevExp",
    prerequisite: true,
    required: false,
  },
};
