export const REQUEST_EVENTS = "REQUEST_EVENTS";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAIL = "GET_EVENTS_FAIL";

export const DELETE_EVENTS = "DELETE_EVENTS";
export const EVENTS_UPDATE = "EVENTS_UPDATE";
export const EVENTS_UPDATE_SUCCESS = "EVENTS_UPDATE_SUCCESS";
export const EVENTS_UPDATE_FAIL = "EVENTS_UPDATE_FAIL";
export const GET_SINGLE_EVENTS = "GET_SINGLE_EVENTS";
export const GET_SINGLE_EVENTS_SUCCESS = "GET_SINGLE_EVENTS_SUCCESS";
export const GET_SINGLE_EVENTS_FAIL = "GET_SINGLE_EVENTS_FAIL";
export const ADD_EVENTS = "ADD_EVENTS";
export const ADD_EVENTS_SUCCESS = "ADD_EVENTS_SUCCESS";
export const ADD_EVENTS_FAIL = "ADD_EVENTS_FAIL";
export const SET_ALERT = "SET_ALERT";
