export const REQUEST_MEMBERS = "REQUEST_MEMBERS";
export const GET_MEMBERS_SUCCESS = "GET_MEMBERS_SUCCESS";
export const GET_MEMBERS_FAIL = "GET_MEMBERS_FAIL";

export const DELETE_MEMBERS = "DELETE_MEMBERS";
export const MEMBERS_UPDATE = "MEMBERS_UPDATE";
export const MEMBERS_UPDATE_SUCCESS = "MEMBERS_UPDATE_SUCCESS";
export const MEMBERS_UPDATE_FAIL = "MEMBERS_UPDATE_FAIL";
export const GET_SINGLE_MEMBERS = "GET_SINGLE_MEMBERS";
export const GET_SINGLE_MEMBERS_SUCCESS = "GET_SINGLE_MEMBERS_SUCCESS";
export const GET_SINGLE_MEMBERS_FAIL = "GET_SINGLE_MEMBERS_FAIL";
export const ADD_MEMBERS = "ADD_MEMBERS";
export const ADD_MEMBERS_SUCCESS = "ADD_MEMBERS_SUCCESS";
export const ADD_MEMBERS_FAIL = "ADD_MEMBERS_FAIL";
export const SET_ALERT = "SET_ALERT";
