export const REQUEST_NEWS = "REQUEST_NEWS";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAIL = "GET_NEWS_FAIL";

export const DELETE_NEWS = "DELETE_NEWS";
export const NEWS_UPDATE = "NEWS_UPDATE";
export const NEWS_UPDATE_SUCCESS = "NEWS_UPDATE_SUCCESS";
export const NEWS_UPDATE_FAIL = "NEWS_UPDATE_FAIL";
export const GET_SINGLE_NEWS = "GET_SINGLE_NEWS";
export const GET_SINGLE_NEWS_SUCCESS = "GET_SINGLE_NEWS_SUCCESS";
export const GET_SINGLE_NEWS_FAIL = "GET_SINGLE_NEWS_FAIL";
export const ADD_NEWS = "ADD_NEWS";
export const ADD_NEWS_SUCCESS = "ADD_NEWS_SUCCESS";
export const ADD_NEWS_FAIL = "ADD_NEWS_FAIL";
export const SET_ALERT = "SET_ALERT";
