export const POST_SUBSCRIBER = "POST_SUBSCRIBER";
export const POST_SUBSCRIBER_SUCCESS = "POST_SUBSCRIBER_SUCCESS";
export const POST_SUBSCRIBER_FAIL = "POST_SUBSCRIBER_FAIL`";
export const CLEAR_SUBSCRIBER_ALERTS = "CLEAR_SUBSCRIBER_ALERTS`";
